### ISSUE TITLE
Setup runs each time

### ISSUE THREAD

**Issue by vedevilolivedev** [GitHubSecurityLab/actions-permissions#15]
I'm not sure if this is expected, but each time the action is ran, the setup.sh attempts to install but fails upon adding mitmproxyuser since it exists already. Since I don't see any teardown in the code anywhere I assume it's not meant to attempt to install every time? Or should it be used with containers?

Edit for clarity/context: Self-hosted Ubuntu runner, Enterprise server.

**Comment by JarLob** [comment]
There is a [post step](https://github.com/GitHubSecurityLab/actions-permissions/blob/main/monitor/action.yml#L19) of the action that runs in the end of the job. You can read more about the GitHub Actions feature [here](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runspost).

However it doesn't do any uninstall because the VM that runs the job is supposed to be [disposed and not reused](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#hardening-for-self-hosted-runners). As far as I know that in case of self-hosted runners the responsibility for isolating the execution environment is left to the user. I'm not sure if it a common practice for self-hosted runners to persist any changes to the system between runs. I have a feeling this may lead if not to security issues, then to non reproducible issue at least.
